package com.example.vsm.model;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "volunteers") // Tells Spring this class maps to the "volunteers" MongoDB collection
@AllArgsConstructor
@NoArgsConstructor
public class Volunteer {
    @Id // Marks this field as the primary key (_id in MongoDB)
    private String id;

    @NotBlank(message = "Name is mandatory") // Validation: name cannot be null/empty
    private String name;

    @Min(value = 18, message = "Minimum age is 18") // Validation: age must be >= 18
    @Max(value = 100, message = "Maximum age is 100") // Validation: age must be <= 100
    private int age;

    @NotBlank(message = "Department is required") // Validation: department must be present
    private String department;

    @NotBlank(message = "Location is required") // Validation: location must be present
    private String location;

    // Getters and setters are generated by Lombok (@Data), but can be explicitly written too
}
